---
## The global configuration for the argocd server
global:
  ## Options for the network policy
  networkPolicy:
    ## Enable the creation of the network policy
    create: true
    ## Deny all ingress traffic by default
    defaultDenyIngress: true

## Configuration for redis high availability
redis-ha:
  ## Enable redis high availability
  enabled: true

## Configuration for the argocd application controller
controller:
  ## Set the number of replicas for the argocd application controller
  replicas: 1

## Configuration for the argocd server
server:
  ## Enable autoscaling for the argocd server
  autoscaling:
    enabled: true
    minReplicas: 2

## Configuration for the repo server
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

## Configuration for the application set controller
applicationSet:
  ## Set the number of replicas for the application set controller
  replicas: 2

## Configuration options for argocd
configs:
  ## Set the timeout for the reconciliation to 180 seconds
  timeout:
    reconciliation: 30s
  ## Specify the admin password for the argocd server - password:
  ## echo -n "admin" | argocd admin initial-password --grpc-web
  ## The password is then hashed using the following command:
  ## echo -n "admin" | argocd admin initial-password --grpc-web | sha256sum
  ## The password is then stored in the secret as a hash
  secret:
    argocdServerAdminPassword: "$2a$10$fDcnV8BQs0kwlCpBnQaGgO8Pm7CLESJEU7DbXit/PIN1jOmlPU6JO"
    argocdServerAdminPasswordMtime: "2025-01-24T19:19:24GMT"
