---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: aws-ack-prometheusservice
  namespace: ack-system
spec:
  # The name the role will have in AWS IAM
  name: aws-ack-prometheusservice
  # Description of the role
  description: "IAM Role used by the AWS ACK Prometheus Service Controller to manage Prometheus Service resources"
  # The trust policy, allowing an entity to assume the role
  assumeRolePolicyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Service": "pods.eks.amazonaws.com"
          },
          "Action": [
            "sts:AssumeRole",
            "sts:TagSession"
          ]
          "Condition": {
            "StringEquals": {
              "aws:RequestTag/kubernetes-namespace": ["ack-system"]
            }
          }
        }
      ]
    }
  policies:
    - arn:aws:iam::aws:policy/AmazonPrometheusConsoleFullAccess
---
apiVersion: eks.services.k8s.aws/v1alpha1
kind: PodIdentityAssociation
metadata:
  name: aws-ack-prometheusservice-association
  namespace: ack-system
spec:
  # The name of the Kubernetes Service Account to associate
  serviceAccount: aws-ack-prometheusservice-controller
  # The Kubernetes Namespace of the Service Account (must match metadata.namespace)
  namespace: ack-system
  # The reference to the IAM role
  roleRef:
    from:
      name: aws-ack-prometheusservice
      namespace: ack-system
  # Tags to apply to the pod identity association
  tags:
    kubernetes-namespace: ack-system
    kubernetes-service-account: aws-ack-prometheusservice-controller
